const WORKOUTActionTypes = {
  GET_WORKOUTS_START: 'GET_WORKOUTS_START',
  GET_WORKOUTS_SUCCESS: 'GET_WORKOUTS_SUCCESS',
  GET_WORKOUTS_FAILURE: 'GET_WORKOUTS_FAILURE',
  CREATE_WORKOUT_START: 'CREATE_WORKOUT_START',
  CREATE_WORKOUT_SUCCESS: 'CREATE_WORKOUT_SUCCESS',
  CREATE_WORKOUT_FAILURE: 'CREATE_WORKOUT_FAILURE',
  DELETE_WORKOUT_START: 'DELETE_WORKOUT_START',
  DELETE_WORKOUT_SUCCESS: 'DELETE_WORKOUT_SUCCESS',
  DELETE_WORKOUT_FAILURE: 'DELETE_WORKOUT_FAILURE',
  GET_WORKOUT_DAYS_START: 'GET_WORKOUT_DAYS_START',
  GET_WORKOUT_DAYS_SUCCESS: 'GET_WORKOUT_DAYS_SUCCESS',
  GET_WORKOUT_DAYS_FAILURE: 'GET_WORKOUT_DAYS_FAILURE',
};

export default WORKOUTActionTypes;