const ExerciseActionTypes = {
  GET_EXERCISES_START: 'GET_EXERCISES_START',
  GET_EXERCISES_SUCCESS: 'GET_EXERCISES_SUCCESS',
  GET_EXERCISES_FAILURE: 'GET_EXERCISES_FAILURE',
  CREATE_EXERCISE_START: 'CREATE_EXERCISES_START',
  CREATE_EXERCISE_SUCCESS: 'CREATE_EXERCISES_SUCCESS',
  CREATE_EXERCISE_FAILURE: 'CREATE_EXERCISES_FAILURE',
  DELETE_EXERCISE_START: 'DELETE_EXERCISE_START',
  DELETE_EXERCISE_SUCCESS: 'DELETE_EXERCISE_SUCCESS',
  DELETE_EXERCISE_FAILURE: 'DELETE_EXERCISE_FAILURE',
  GET_EXERCISE_CHART_START: 'GET_EXERCISE_CHART_START',
  GET_EXERCISE_CHART_SUCCESS: 'GET_EXERCISE_CHART_SUCCESS',
  GET_EXERCISE_CHART_FAILURE: 'DELETE_EXERCISE_FAILURE',
};

export default ExerciseActionTypes;