const RoutineActionTypes = {
  GET_ROUTINES_START: 'GET_ROUTINES_START',
  GET_ROUTINES_SUCCESS: 'GET_ROUTINES_SUCCESS',
  GET_ROUTINES_FAILURE: 'GET_ROUTINES_FAILURE',
  GET_ROUTINE_START: 'GET_ROUTINE_START',
  GET_ROUTINE_SUCCESS: 'GET_ROUTINE_SUCCESS',
  GET_ROUTINE_FAILURE: 'GET_ROUTINE_FAILURE',
  CREATE_ROUTINE_START: 'CREATE_ROUTINE_START',
  CREATE_ROUTINE_SUCCESS: 'CREATE_ROUTINE_SUCCESS',
  CREATE_ROUTINE_FAILURE: 'CREATE_ROUTINE_FAILURE',
  DELETE_ROUTINE_START: 'DELETE_ROUTINE_START',
  DELETE_ROUTINE_SUCCESS: 'DELETE_ROUTINE_SUCCESS',
  DELETE_ROUTINE_FAILURE: 'DELETE_ROUTINE_FAILURE'
};

export default RoutineActionTypes;